name: Example - Deploy and Invalidate CloudFront

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      # Build and deploy steps would go here
      # ...

      - name: Invalidate CloudFront Cache
        id: invalidate
        uses: ./.github/actions/cloudfront-invalidate
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: '/*'
          # Optional: Specify specific paths
          # paths: '/index.html,/assets/*,/css/*,/js/*'
        
      # You can use the invalidation ID in subsequent steps
      - name: Use invalidation ID
        run: echo "Invalidation ID: ${{ steps.invalidate.outputs.invalidation-id }}"