AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS End-to-End Deployment Example - ALB Stack'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)

  VpcId:
    Type: String
    Description: VPC ID

  PublicSubnet1:
    Type: String
    Description: Public Subnet 1 ID

  PublicSubnet2:
    Type: String
    Description: Public Subnet 2 ID

  HealthCheckPath:
    Type: String
    Default: /health
    Description: Health check path

  ListenerPort:
    Type: Number
    Default: 80
    Description: ALB listener port
    
  HttpsListenerPort:
    Type: Number
    Default: 443
    Description: ALB HTTPS listener port

  SecurityGroupTag:
    Type: String
    Default: awse2e-alb-sg
    Description: Tag for the ALB security group

  LoadBalancerName:
    Type: String
    Default: awse2e-alb
    Description: Name of the Application Load Balancer

  TargetGroupName:
    Type: String
    Default: awse2e-tg
    Description: Name of the target group
    
  CertificateArn:
    Type: String
    Description: ARN of the ACM certificate for HTTPS
    
  # S3LogBucket parameter removed as we're not using S3 for logging

Resources:
  # ALB Security Group
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ListenerPort
          ToPort: !Ref ListenerPort
          CidrIp: 0.0.0.0/0
          Description: "Allow HTTP access from anywhere (required for public API access)"
        - IpProtocol: tcp
          FromPort: !Ref HttpsListenerPort
          ToPort: !Ref HttpsListenerPort
          CidrIp: 0.0.0.0/0
          Description: "Allow HTTPS access from anywhere (required for public API access)"
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-${SecurityGroupTag}"
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: "awse2e"
        - Key: ManagedBy
          Value: "CloudFormation"

  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${Environment}-${LoadBalancerName}"
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '60'
        # Access logging removed - using CloudWatch for application logging instead
        # Add security policies
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: 'true'
        - Key: deletion_protection.enabled
          Value: 'false'
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${Environment}-${LoadBalancerName}"
        - Key: Application
          Value: "awse2e"
        - Key: ManagedBy
          Value: "CloudFormation"

  # Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${Environment}-${TargetGroupName}"
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${Environment}-${TargetGroupName}"
        - Key: Application
          Value: "awse2e"
        - Key: ManagedBy
          Value: "CloudFormation"

  # HTTP Listener - redirects to HTTPS
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: !Ref ListenerPort
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: !Ref HttpsListenerPort
            StatusCode: HTTP_301
            
  # HTTPS Listener
  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: !Ref HttpsListenerPort
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  LoadBalancerDnsName:
    Description: DNS name of the load balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub "${AWS::StackName}-LoadBalancerDnsName"

  LoadBalancerArn:
    Description: ARN of the load balancer
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub "${AWS::StackName}-LoadBalancerArn"

  TargetGroupArn:
    Description: ARN of the target group
    Value: !Ref TargetGroup
    Export:
      Name: !Sub "${AWS::StackName}-TargetGroupArn"
      
  ALBSecurityGroupId:
    Description: Security Group ID of the ALB
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-ALBSecurityGroupId"
