AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Deployment - Cognito User Pool for Authentication'

Parameters:
  ApplicationName:
    Type: String
    Description: Name of the application

  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)

  UserPoolName:
    Type: String
    Default: UserPool
    Description: Name of the Cognito User Pool

  ClientName:
    Type: String
    Default: AppClient
    Description: Name of the Cognito App Client

  DomainName:
    Type: String
    Description: Domain name for the application

  AuthDomainName:
    Type: String
    Description: Domain name for the Cognito User Pool domain

  CertificateArn:
    Type: String
    Description: ARN of the ACM certificate for the custom domain

  EmailVerificationSubject:
    Type: String
    Default: "Verify your email for our app"
    Description: Subject for email verification

  EmailVerificationMessage:
    Type: String
    Default: "Thank you for signing up! Your verification code is {####}"
    Description: Message for email verification

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${ApplicationName}-${Environment}-${UserPoolName}"
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: !Ref EmailVerificationMessage
      EmailVerificationSubject: !Ref EmailVerificationSubject
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: given_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      MfaConfiguration: "OFF"
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserPoolTags:
        Environment: !Ref Environment
        Application: !Ref ApplicationName
        ManagedBy: "CloudFormation"

  # Cognito App Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${ApplicationName}-${Environment}-${ClientName}"
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      AccessTokenValidity: 1
      IdTokenValidity: 1
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Sub "https://${DomainName}"
        - "http://localhost:3000"
      LogoutURLs:
        - !Sub "https://${DomainName}"
        - "http://localhost:3000"
      AllowedOAuthFlows:
        - implicit
        - code
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true

  # # Domain for Cognito (optional, for hosted UI)
  # UserPoolDomain:
  #   Type: AWS::Cognito::UserPoolDomain
  #   Properties:
  #     Domain: !Ref AuthDomainName
  #     UserPoolId: !Ref UserPool
  #     CustomDomainConfig:
  #       CertificateArn: !Ref CertificateArn

Outputs:
  UserPoolId:
    Description: ID of the Cognito User Pool
    Value: !Ref UserPool
    Export:
      Name: !Sub "${ApplicationName}-${Environment}-UserPoolId"

  UserPoolArn:
    Description: ARN of the Cognito User Pool
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub "${ApplicationName}-${Environment}-UserPoolArn"

  UserPoolClientId:
    Description: ID of the Cognito User Pool Client
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "${ApplicationName}-${Environment}-UserPoolClientId"

  UserPoolDomainName:
    Description: Domain name for the Cognito User Pool
    Value: !Sub "https://${AuthDomainName}"
    Export:
      Name: !Sub "${ApplicationName}-${Environment}-UserPoolDomainName"