AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Deployment - ECR Stack'

Parameters:
  ApplicationName:
    Type: String
    Description: Name of the application

  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)

  ServiceName:
    Type: String
    Description: Name of the service

Resources:
  BackendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${ApplicationName}-${Environment}-${ServiceName}-repo"
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: KMS
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Service
          Value: !Ref ServiceName
        - Key: ManagedBy
          Value: "CloudFormation"

Outputs:
  RepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt BackendRepository.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryUri"

  RepositoryName:
    Description: ECR Repository Name
    Value: !Ref BackendRepository
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryName"
