AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS End-to-End Deployment Example - ECR Stack'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
  
  RepositoryName:
    Type: String
    Description: Name of the ECR repository

Resources:
  BackendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${Environment}-${RepositoryName}"
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 10 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  RepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt BackendRepository.RepositoryUri
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryUri"

  RepositoryName:
    Description: ECR Repository Name
    Value: !Ref BackendRepository
    Export:
      Name: !Sub "${AWS::StackName}-RepositoryName"
