AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS End-to-End Deployment Example - Logging Stack'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)

Resources:
  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${Environment}-awse2e"
      RetentionInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  LogGroupArn:
    Description: CloudWatch Log Group ARN
    Value: !Ref LogGroup
    Export:
      Name: !Sub "${AWS::StackName}-LogGroupId"
