AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS End-to-End Deployment Example - Logging Stack'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
    
  RetentionInDays:
    Type: Number
    Default: 30
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Description: Number of days to retain logs

Resources:
  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${Environment}-awse2e"
      RetentionInDays: !Ref RetentionInDays
      KmsKeyId: !GetAtt LoggingKmsKey.Arn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${Environment}-awse2e-logs"
        - Key: Application
          Value: "awse2e"
        - Key: ManagedBy
          Value: "CloudFormation"
          
  # KMS Key for Log Encryption
  LoggingKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for encrypting CloudWatch Logs
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
            Resource: '*'
          - Sid: Allow CloudWatch Logs
            Effect: Allow
            Principal:
              Service: logs.amazonaws.com
            Action:
              - kms:Encrypt*
              - kms:Decrypt*
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:Describe*
            Resource: '*'
            Condition:
              ArnEquals:
                kms:EncryptionContext:aws:logs:arn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/${Environment}-awse2e"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub "${Environment}-awse2e-logs-key"
        - Key: Application
          Value: "awse2e"
        - Key: ManagedBy
          Value: "CloudFormation"
          
  # KMS Key Alias
  LoggingKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${Environment}-awse2e-logs-key"
      TargetKeyId: !Ref LoggingKmsKey

Outputs:
  LogGroupArn:
    Description: CloudWatch Log Group ARN
    Value: !GetAtt LogGroup.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LogGroupArn"

  LogGroupName:
    Description: CloudWatch Log Group Name
    Value: !Ref LogGroup
    Export:
      Name: !Sub "${AWS::StackName}-LogGroupName"

  LoggingKmsKeyArn:
    Description: KMS Key ARN for Logging
    Value: !GetAtt LoggingKmsKey.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LoggingKmsKeyArn"
