name: Deploy ECS API Task Definition and Service

on:
  workflow_call:
    inputs:
      LoadBalancerDnsName:
        required: true
        type: string
        description: The DNS name of the load balancer for the ECS service.

jobs:
  deploy-cloudfront:
    name: Deploy CloudFront Infrastructure
    runs-on: ubuntu-latest
    outputs:
      RepositoryUri: ${{ steps.deploy-ecr-stack.outputs.RepositoryUri }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy CloudFront Stack
        id: deploy-cloudfront-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ECRStack
          template: iac/cloudfront.yaml
          parameters: |
            Environment=${{ env.ENVIRONMENT }}
            DomainName=${{ env.DOMAIN_NAME }}
            CertificateArn=${{ secrets.ACM_CERTIFICATE_ARN }}
            ApiEndpoint=${{ inputs.LoadBalancerDnsName }}            
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: "1"
