name: Deploy AWS End-to-End Example

on:
  workflow_dispatch:

jobs:
  # Deploy backend infrastructure (Logging, Networking, ECS Cluster)
  deploy-backend-infrastructure:
    name: Deploy Backend Infrastructure
    uses: ./.github/workflows/deploy-backend-infrastructure.yaml

  # Deploy API service (ECS Task/Service, ALB)
  deploy-api-service:
    name: Deploy API Service
    uses: ./.github/workflows/deploy-api-service.yaml
    needs: deploy-backend-infrastructure
    with:
      ECSClusterName: ${{ needs.deploy-backend-infrastructure.outputs.ClusterName }}
      TargetGroupArn: ${{ needs.deploy-backend-infrastructure.outputs.TargetGroupArn }}
      LogGroupArn: ${{ needs.deploy-backend-infrastructure.outputs.LogGroupArn }}
      VpcId: ${{ needs.deploy-backend-infrastructure.outputs.VpcId }}
      PublicSubnet1: ${{ needs.deploy-backend-infrastructure.outputs.PublicSubnet1 }}
      PublicSubnet2: ${{ needs.deploy-backend-infrastructure.outputs.PublicSubnet2 }}

  # Deploy other microservices...

  # Deploy frontend infrastructure (S3, CloudFront)
  deploy-frontend-infrastructure:
    name: Deploy Frontend Infrastructure
    uses: ./.github/workflows/deploy-frontend-infrastructure.yaml
    needs: deploy-backend-infrastructure
    with:
      LoadBalancerDnsName: ${{ needs.deploy-api-service.outputs.LoadBalancerDnsName }}

  # Deploy frontend
  deploy-frontend:
    name: Deploy Frontend
    uses: ./.github/workflows/deploy-frontend.yaml
    needs: deploy-frontend-infrastructure
    with:
      LoadBalancerDnsName: ${{ needs.deploy-api-service.outputs.LoadBalancerDnsName }}
      BucketName: ${{ needs.deploy-frontend-infrastructure.outputs.BucketName }}
      CloudFrontDistributionId: ${{ needs.deploy-frontend-infrastructure.outputs.CloudFrontDistributionId }}
